release_github:
  stage: deploy
  image: docker.reallserver.cn/public/docker-git
  only:
  - master
  script:
  - git push -u --set-upstream https://${github_key}@github.com/SilverBlogTeam/silverblog_ios.git HEAD:master
