release_github:
  stage: deploy
  image: docker.reallserver.cn/public/docker-git
  only:
  - master
  script:
  - git config --global http.https://github.com.proxy socks5://192.168.3.8:1086
  - git push -u --set-upstream https://${github_key}@github.com/SilverBlogTeam/silverblog_ios.git HEAD:master
