release_github:
  stage: deploy
  only:
  - master
  script:
  - eval $(ssh-agent -s)
  - ssh-add - <<< $(curl https://keystore.reallserver.cn/gitlab-sshkey/id_ecdsa -o deploy.key -u gitlab:${key_store_passwd})
  - git push --set-upstream git@github.com:SilverBlog/silverblog_ios.git HEAD:$CI_COMMIT_REF_NAME
