platform :ios, '12.0'
use_frameworks!
project '../silverblog.xcodeproj'
target 'silverblog' do
  pod 'Alamofire','= 4.9.1'
  pod 'SwiftyJSON','~> 5.0.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.0'
end
target 'silverblog_share' do
  pod 'Alamofire','= 4.9.1'
end
