platform :ios, '11.4'
use_frameworks!
project '../silverblog.xcodeproj'
target 'silverblog' do
  pod 'Alamofire','~> 4.7'
  pod 'SwiftyJSON','~> 4.0'
  pod 'IQKeyboardManagerSwift', '~> 6.0.1'
end
target 'silverblog_share' do
  pod 'Alamofire','~> 4.7'
end
